### ISSUE TITLE
feature: add 'count' property/method or __len__ to Table to get the number of rows

### ISSUE THREAD

**Issue by garaud** [yhat/db.py#63]
Hi,

I would like to get the number of rows in a specific table. Is it possible to add a `count` or `rows` method/property to the `Table` class? You can also add the `__len__` special method.

Moreover, this *number of rows* will be added to the `TableSet` repr.

Cheers,
Damien

**Comment by maurobaraldi** [comment]
The line counting feature has different implementations between databases. The best approach here, could be to count the result from `all` method in class `Tables`.  I think it should be a property.

**Comment by glamp** [comment]
@maurobaraldi  :+1:

**Comment by maurobaraldi** [comment]
This issue can be closed. The pull request (64)[https://github.com/yhat/db.py/pull/64] already merged, meet the needs of this request.

**Comment by garaud** [comment]
Quite efficient and responsive. Thanks !!
